### ISSUE TITLE
/bin/python doesn't exist in raspbian

### ISSUE THREAD

**Issue by ieguiguren** [jibbius/raspberry_pi_photo_booth#1]
Hi.

When trying to execute the code directly there is an error reaching the interpreter.
```
pi@raspberrypi:~/raspberry_pi_photo_booth $ lsb_release -a
No LSB modules are available.
Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 9.1 (stretch)
Release:	9.1
Codename:	stretch
pi@raspberrypi:~/raspberry_pi_photo_booth $ ./camera.py 
-bash: ./camera.py: /bin/python: bad interpreter: No such file or directory
pi@raspberrypi:~/raspberry_pi_photo_booth $ which python
/usr/bin/python

```

Although in the instructions it says to execute it as:

> 5. Run:
`python camera.py`

it has no meaning to have the shebang if it avoids execution of the program.
During the years I've discovered the 'env' command and works like a charm. It's actually present in all my python files:
`#!/usr/bin/env python`
This will look for the python command in the PATH routes.

**Comment by jibbius** [comment]
Good pickup, thanks.
