### ISSUE TITLE
Print photo with Cups

### ISSUE THREAD

**Issue by ricochebonjour** [jibbius/raspberry_pi_photo_booth#3]
Hello man, I'm trying to do an automatic print with a thermal TM-T20II who works with Cups.
Can you take a look at my code, I'm confused about when the print process has to start...
[https://github.com/ricochebonjour/raspberry_pi_photo_booth/commit/7ed71e48094f0351551c47ea61d12b102f707f03](https://github.com/ricochebonjour/raspberry_pi_photo_booth/commit/7ed71e48094f0351551c47ea61d12b102f707f03)

**Comment by jibbius** [comment]
Hi,
Is the intention that each of the four frames is printed as a separate print?

Without looking into Cups at all, it looks like the line of code;
‘printCups(photo_number, filename_prefix)‘

... might need to be raised up slightly, and indented, so much that it is in the same code block as the ‘taking_photo’ line?

Let me know how you go, and I can look at tomorrow if still stuck.

**Comment by ricochebonjour** [comment]
I get this with printCups in the same block code as 'taking_photo' :
`Welcome to the photo booth!
Press the button to take a photo
Button pressed! You folks are in for a treat!
             ...3
             ...2
             ...1
Photo (1) saved: /home/pi/raspberry_pi_photo_booth/photos/2018-03-12_19-33-19_1of4.jpg
unexpected error:  [Errno 2] No such file or directory: '/home/pi/raspberry_pi_photo_booth/photos/2018-03-12_19-33-19/1of4.jpg'`

I get this with printCups at the end :
`Welcome to the photo booth!
Press the button to take a photo
Button pressed! You folks are in for a treat!
             ...3
             ...2
             ...1
Photo (1) saved: /home/pi/raspberry_pi_photo_booth/photos/2018-03-12_18-55-32_1of4.jpg
             ...3
             ...2
             ...1
Photo (2) saved: /home/pi/raspberry_pi_photo_booth/photos/2018-03-12_18-55-32_2of4.jpg
             ...3
             ...2
             ...1
Photo (3) saved: /home/pi/raspberry_pi_photo_booth/photos/2018-03-12_18-55-32_3of4.jpg
             ...3
             ...2
             ...1
Photo (4) saved: /home/pi/raspberry_pi_photo_booth/photos/2018-03-12_18-55-32_4of4.jpg
unexpected error:  [Errno 2] No such file or directory: '/home/pi/raspberry_pi_photo_booth/photos/2018-03-12_18-55-32/4of4.jpg'`

**Comment by ricochebonjour** [comment]
Changed filename values in printCups and now get this;
`Welcome to the photo booth!
Press the button to take a photo
Button pressed! You folks are in for a treat!
             ...3
             ...2
             ...1
Photo (1) saved: /home/pi/raspberry_pi_photo_booth/photos/2018-03-12_19-45-33_1of1.jpg
unexpected error:  'dict_keys' object does not support indexing`

**Comment by jibbius** [comment]
Great, file name error is now fixed.

Re: dict_name, do you get the same problem using python2 instead of python3?

I’m looking at this;
https://stackoverflow.com/questions/17322668/typeerror-dict-keys-object-does-not-support-indexing

**Comment by ricochebonjour** [comment]
Yeah, I try to find what's wrong with printer_name = printers.keys()[0] to change it.

I get this with python2; 
('unexpected error: ', 'unicode or bytes object required')

Edit : Changed the code with your stackoverflow link ! 👍 
Now got the same error in python3

**Comment by jibbius** [comment]
Possibly an issue with this line;
`conn.printFile("Printing", photo_number, "from", filename_prefix,{"copies": "1"})`

Possibly needs to be something like:
```
title = "Photo " + photo_number
conn.printFile(printer_name, filename, title,{"copies": "1"})
```

**Comment by ricochebonjour** [comment]
Hi Jack,
Yes there was an issue with conn.printFile fixed with this;
'conn.printFile(printer_name, photo_number, filename_prefix,{"copies": "1"})'

And a line was missing in printCups to enable the printer;
'conn.enablePrinter(printer_name)'

Thank's for your help !

Now I would like to manage a dither filter on the photo before it goes to the thermal printer... :)

**Comment by jibbius** [comment]
Glad to hear is now solved!
Good luck with the rest of the build.
Would be great to see what your finished photo booth looks like (if you’re happy to share).

Cheers,
Jack

**Comment by ricochebonjour** [comment]
For sure !
Cheers,
