### ISSUE TITLE
Bad overlay_image call on prep_for_photo_screen function

### ISSUE THREAD

**Issue by KsmoinO** [jibbius/raspberry_pi_photo_booth#5]
Hello,

I think there is one extra parameter (or one is missing) at @234 :
`overlay_image(get_ready_image, PREP_DELAY, 'RGBA')`

It should be :
`overlay_image(get_ready_image, PREP_DELAY)`
or maybe
`overlay_image(get_ready_image, PREP_DELAY,3,'RGBA')`

**Comment by jibbius** [comment]
You're absolutely right.
Thank you!
